{
  "openapi": "3.0.1",
  "info": {
    "title": "API V1",
    "version": "v1"
  },
  "paths": {
    "/api/v1/ebooks": {
      "get": {
        "summary": "Retrieves all ebooks",
        "tags": [
          "Ebooks"
        ],
        "responses": {
          "200": {
            "description": "ebooks found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "title": {
                        "type": "string"
                      },
                      "description": {
                        "type": "string"
                      },
                      "isbn": {
                        "type": "string"
                      },
                      "price": {
                        "type": "number"
                      }
                    },
                    "required": [
                      "id",
                      "title",
                      "description",
                      "isbn",
                      "price"
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Creates a new ebook",
        "tags": [
          "Ebooks"
        ],
        "parameters": [],
        "responses": {
          "201": {
            "description": "ebook created"
          },
          "422": {
            "description": "invalid request"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  },
                  "isbn": {
                    "type": "string"
                  },
                  "price": {
                    "type": "number"
                  }
                },
                "required": [
                  "title",
                  "description",
                  "isbn",
                  "price"
                ]
              }
            }
          }
        }
      }
    },
    "/api/v1/ebooks/{id}": {
      "get": {
        "summary": "Retrieves a single ebook",
        "tags": [
          "Ebooks"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "ebook found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "title": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "isbn": {
                      "type": "string"
                    },
                    "price": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "id",
                    "title",
                    "description",
                    "isbn",
                    "price"
                  ]
                }
              }
            }
          },
          "404": {
            "description": "ebook not found"
          }
        }
      },
      "patch": {
        "summary": "Updates an existing ebook",
        "tags": [
          "Ebooks"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "ebook updated"
          },
          "404": {
            "description": "ebook not found"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  },
                  "isbn": {
                    "type": "string"
                  },
                  "price": {
                    "type": "number"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Deletes an ebook",
        "tags": [
          "Ebooks"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "ebook deleted"
          },
          "404": {
            "description": "ebook not found"
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "http://localhost:3000",
      "description": "Development server"
    }
  ]
}